declare_platform(manul KernelPlatformManul PLAT_MANUL KernelArchRiscV)
if(KernelPlatformManul)
    declare_seL4_arch(riscv64)
    config_set(KernelPlatformFirstHartID FIRST_HART_ID 0)
    config_set(KernelOpenSBIPlatform OPENSBI_PLATFORM "generic")
    config_option(KernelManulQemu MANUL_QEMU "Manul IRQ tests on QEMU virt" DEFAULT OFF)
    if(KernelManulQemu)
        set(manul_timer_frequency 10000000)
    else()
        set(manul_timer_frequency 150000000)
    endif()
    list(APPEND KernelDTSList "${CMAKE_CURRENT_LIST_DIR}/manul.dts")
    config_option(KernelManulFullRam MANUL_FULL_RAM "Expose all 32 GiB of Manul DDR" DEFAULT OFF)
    if(KernelManulFullRam)
        if(KernelManulQemu)
            message(FATAL_ERROR "The current QEMU runner provides only 4 GiB")
        endif()
        list(APPEND KernelDTSList "${CMAKE_CURRENT_LIST_DIR}/full-ram.dts")
    endif()
    config_option(KernelRiscvAia RISCV_AIA "Use APLIC/IMSIC external interrupts" DEFAULT OFF)
    if(KernelRiscvAia)
        if(KernelMaxNumNodes GREATER 1)
            if(NOT KernelMaxNumNodes STREQUAL "4")
                message(FATAL_ERROR "Manul supports one or four harts")
            endif()
            list(APPEND KernelDTSList "${CMAKE_CURRENT_LIST_DIR}/smp.dts")
        endif()
        list(APPEND KernelDTSList "${CMAKE_CURRENT_LIST_DIR}/aia.dts")
        declare_default_headers(TIMER_FREQUENCY ${manul_timer_frequency} MAX_IRQ 31
            INTERRUPT_CONTROLLER drivers/irq/riscv_aia.h)
    else()
    declare_default_headers(TIMER_FREQUENCY ${manul_timer_frequency} MAX_IRQ 0
        INTERRUPT_CONTROLLER drivers/irq/riscv_plic_dummy.h)
    endif()
    if(KernelManulQemu)
        list(APPEND KernelDTSList "${CMAKE_CURRENT_LIST_DIR}/qemu.dts")
    endif()
endif()
